### ISSUE TITLE
Where is the Contribution/Credits

### ISSUE THREAD

**Issue by Olink** [nicatronTg/fixed-interops#1]
As the owner of said changes, I believe that you must provide a Credits section for me ;)

**Comment by hakusaro** [comment]
Fixed in 6606fcf2144e180c7e5ca982472f0b9a6cfce914 ;)

**Comment by Olink** [comment]
Thanks, was afraid I'd have to DMCA you :+1:

**Comment by hakusaro** [comment]
Why is (kappa) not an emote on github :(
